### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by emirsassan** [emirsassan/anisto#3]
- [ ] Import and export files
- [ ] Compile functionality
- [ ] Live preview for in-game message box
- [ ] Full refactor of the codebase
- [ ] Include bustup portraits
- [ ] Include all icons related to controls
- [ ] Include all icons related to stats
- [ ] Welcome or first start tour of editor
